"""Generate emotion + neutral story corpora via OpenAI (gpt-4o-mini).

Usage:
    # Full corpus (all DEFAULT_EMOTIONS + N_NEUTRAL_STORIES)
    python data/generate_stories.py

    # Only generate for a subset (e.g. just the 20 new emotions), APPEND
    # to the existing emotion_stories.json rather than overwriting.
    python data/generate_stories.py --only ecstatic,thrilled,...

    # Skip neutral stories entirely.
    python data/generate_stories.py --no-neutral

Requires OPENAI_API_KEY.
"""
from __future__ import annotations
import argparse
import asyncio
import json
import os
import random
import sys
from pathlib import Path

# Make the emotionvec package importable when running this script directly.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from emotionvec.config import (
    DEFAULT_EMOTIONS,
    N_STORIES_PER_EMOTION,
    N_NEUTRAL_STORIES,
    DATA_DIR,
    EMOTION_STORIES_NAME,
    NEUTRAL_STORIES_NAME,
)
from openai import AsyncOpenAI
from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parents[1] / ".env")
load_dotenv(Path(__file__).resolve().parents[2] / ".env")

EMOTION_STORIES_PATH = DATA_DIR / EMOTION_STORIES_NAME
NEUTRAL_STORIES_PATH = DATA_DIR / NEUTRAL_STORIES_NAME

MODEL = "gpt-4o-mini"

EMOTION_SETTINGS = [
    "at a wedding", "during a morning commute", "in an empty office late at night",
    "on a crowded bus", "in the kitchen making breakfast", "at the beach",
    "during a job interview", "in a forest trail", "at a family dinner",
    "during a long-distance call", "in a crowded airport", "at a doctor's office",
    "while walking the dog", "on a first date", "in a library",
    "during a thunderstorm", "at a concert", "while moving into a new apartment",
    "on a rainy afternoon", "in a hospital waiting room", "during a hike",
    "at a birthday party", "at the grocery store", "while cleaning the attic",
    "during an art class", "on a crowded train", "at a high school reunion",
    "in a coffee shop", "on a snowy morning", "while fixing a broken bicycle",
]

EMOTION_PROMPT = """Write a short first-person story (about 150 words) in which the narrator clearly experiences the emotion of {emotion}. Show the emotion through thoughts, actions, and bodily sensations — do not name the emotion explicitly nor use obvious synonyms. The setting should be: {setting}.

Return only the story text — no title, no preamble, no quotes."""

NEUTRAL_TOPICS = [
    "the life cycle of a honey bee",
    "the geological formation of basalt columns",
    "the history of the wheel",
    "the role of mitochondria in eukaryotic cells",
    "how tides are generated by lunar gravity",
    "the Byzantine Empire under Justinian I",
    "the electromagnetic spectrum from radio waves to gamma rays",
    "plate tectonics and continental drift",
    "the invention of movable type printing",
    "the structure of DNA",
    "monsoon seasons in South Asia",
    "how cheese is made industrially",
    "the Roman aqueduct system",
    "the ecology of coral reefs",
    "Newton's three laws of motion",
    "the specifications of a typical mid-range laptop processor",
    "the technical features of a modern espresso machine",
    "dimensions and capacity of a standard shipping container",
    "the main components of a bicycle drivetrain",
    "how induction cooktops generate heat",
    "how HTTP requests are routed through the internet",
    "the process of photosynthesis at the molecular level",
    "how water is purified for municipal supply",
    "the mechanics of a four-stroke internal combustion engine",
    "how digital cameras convert light into images",
    "how GPS triangulation determines a receiver's position",
    "the refining of crude oil into gasoline",
    "how hydroelectric dams generate electricity",
    "the pasteurization of milk",
    "how semiconductor transistors work",
    "the procedure for making sourdough bread",
    "how to prune a fruit tree in winter",
    "the steps to change a car tire",
    "the standard procedure for brewing pour-over coffee",
    "how to rotate crops on a small farm",
    "the method for tuning a violin",
    "the process of composting kitchen scraps",
    "how to wire a three-way light switch",
    "the standard routine for oil changes in a passenger vehicle",
    "how to set up a small aquarium",
]

NEUTRAL_PROMPT = """Write a short factual, emotionally flat paragraph (about 150 words) describing {topic}. Use neutral, encyclopedic, third-person prose. No characters, no narrative, no emotional language. Just facts, definitions, and mechanisms.

Return only the paragraph — no heading, no quotes."""


async def gen_one(client: AsyncOpenAI, prompt: str, attempt: int = 0) -> str:
    try:
        resp = await client.chat.completions.create(
            model=MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.9 if attempt == 0 else 1.0,
            max_tokens=400,
        )
        return resp.choices[0].message.content.strip()
    except Exception:
        if attempt < 2:
            await asyncio.sleep(1 + attempt)
            return await gen_one(client, prompt, attempt + 1)
        raise


async def gen_emotion_story(client, emotion: str, setting: str) -> dict:
    text = await gen_one(client, EMOTION_PROMPT.format(emotion=emotion, setting=setting))
    return {"emotion": emotion, "setting": setting, "text": text}


async def gen_neutral_story(client, topic: str) -> dict:
    text = await gen_one(client, NEUTRAL_PROMPT.format(topic=topic))
    return {"topic": topic, "text": text}


async def run(only: list[str] | None, do_neutral: bool, append: bool,
              n_emotion: int, n_neutral: int) -> None:
    client = AsyncOpenAI(api_key=os.environ["OPENAI_API_KEY"])
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    rng = random.Random(42)

    target_emotions = only if only else DEFAULT_EMOTIONS
    print(f"Generating stories for {len(target_emotions)} emotions ({n_emotion} each)…",
          flush=True)

    tasks = []
    for emotion in target_emotions:
        settings = rng.sample(EMOTION_SETTINGS, n_emotion)
        for s in settings:
            tasks.append(gen_emotion_story(client, emotion, s))
    print(f"  total: {len(tasks)} emotion stories", flush=True)

    results = []
    for i in range(0, len(tasks), 40):
        chunk = tasks[i:i + 40]
        results.extend(await asyncio.gather(*chunk))
        print(f"  emotion stories done: {len(results)}/{len(tasks)}", flush=True)

    if append and EMOTION_STORIES_PATH.exists():
        existing = json.loads(EMOTION_STORIES_PATH.read_text())
        # Drop any existing entries for emotions we're regenerating.
        existing = [r for r in existing if r.get("emotion") not in set(target_emotions)]
        results = existing + results

    EMOTION_STORIES_PATH.write_text(json.dumps(results, indent=1, ensure_ascii=False))
    print(f"Wrote {EMOTION_STORIES_PATH} ({len(results)} stories, "
          f"{len({r['emotion'] for r in results})} emotions)")

    if do_neutral:
        topics = []
        while len(topics) < n_neutral:
            topics.extend(rng.sample(NEUTRAL_TOPICS, len(NEUTRAL_TOPICS)))
        topics = topics[:n_neutral]

        neu_tasks = [gen_neutral_story(client, t) for t in topics]
        print(f"Generating {len(neu_tasks)} neutral stories…", flush=True)
        neu_results = []
        for i in range(0, len(neu_tasks), 40):
            chunk = neu_tasks[i:i + 40]
            neu_results.extend(await asyncio.gather(*chunk))
            print(f"  neutral done: {len(neu_results)}/{len(neu_tasks)}", flush=True)
        NEUTRAL_STORIES_PATH.write_text(json.dumps(neu_results, indent=1, ensure_ascii=False))
        print(f"Wrote {NEUTRAL_STORIES_PATH}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--only", default=None,
                    help="Comma-separated subset of emotions to (re)generate.")
    ap.add_argument("--no-neutral", action="store_true",
                    help="Skip neutral stories (keep the existing ones on disk).")
    ap.add_argument("--append", action="store_true",
                    help="Merge new stories into an existing emotion_stories.json "
                         "(overwrites any entries for the --only emotions).")
    ap.add_argument("--n-per-emotion", type=int, default=N_STORIES_PER_EMOTION)
    ap.add_argument("--n-neutral", type=int, default=N_NEUTRAL_STORIES)
    args = ap.parse_args()

    only = [e.strip() for e in args.only.split(",")] if args.only else None
    asyncio.run(run(only, not args.no_neutral, args.append,
                    args.n_per_emotion, args.n_neutral))


if __name__ == "__main__":
    main()
