"""Generate emotion and neutral story corpora using OpenAI (gpt-4o-mini).

Uses async concurrency; stories are retried on parse failures.
"""
import asyncio
import json
import os
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from config import (
    EMOTIONS,
    N_STORIES_PER_EMOTION,
    N_NEUTRAL_STORIES,
    EMOTION_STORIES_PATH,
    NEUTRAL_STORIES_PATH,
    DATA_DIR,
)

from openai import AsyncOpenAI
from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parents[2] / ".env")

client = AsyncOpenAI(api_key=os.environ["OPENAI_API_KEY"])
MODEL = "gpt-4o-mini"

EMOTION_SETTINGS = [
    "at a wedding", "during a morning commute", "in an empty office late at night",
    "on a crowded bus", "in the kitchen making breakfast", "at the beach",
    "during a job interview", "in a forest trail", "at a family dinner",
    "during a long-distance call", "in a crowded airport", "at a doctor's office",
    "while walking the dog", "on a first date", "in a library",
    "during a thunderstorm", "at a concert", "while moving into a new apartment",
    "on a rainy afternoon", "in a hospital waiting room", "during a hike",
    "at a birthday party", "at the grocery store", "while cleaning the attic",
    "during an art class", "on a crowded train", "at a high school reunion",
    "in a coffee shop", "on a snowy morning", "while fixing a broken bicycle",
]

EMOTION_PROMPT = """Write a short first-person story (about 150 words) in which the narrator clearly experiences the emotion of {emotion}. Show the emotion through thoughts, actions, and bodily sensations — do not name the emotion explicitly nor use obvious synonyms. The setting should be: {setting}.

Return only the story text — no title, no preamble, no quotes."""

NEUTRAL_TOPICS = [
    # Wikipedia-style facts
    "the life cycle of a honey bee",
    "the geological formation of basalt columns",
    "the history of the wheel",
    "the role of mitochondria in eukaryotic cells",
    "how tides are generated by lunar gravity",
    "the Byzantine Empire under Justinian I",
    "the electromagnetic spectrum from radio waves to gamma rays",
    "plate tectonics and continental drift",
    "the invention of movable type printing",
    "the structure of DNA",
    "monsoon seasons in South Asia",
    "how cheese is made industrially",
    "the Roman aqueduct system",
    "the ecology of coral reefs",
    "Newton's three laws of motion",
    # product specs
    "the specifications of a typical mid-range laptop processor",
    "the technical features of a modern espresso machine",
    "dimensions and capacity of a standard shipping container",
    "the main components of a bicycle drivetrain",
    "how induction cooktops generate heat",
    # technical descriptions
    "how HTTP requests are routed through the internet",
    "the process of photosynthesis at the molecular level",
    "how water is purified for municipal supply",
    "the mechanics of a four-stroke internal combustion engine",
    "how digital cameras convert light into images",
    "how GPS triangulation determines a receiver's position",
    "the refining of crude oil into gasoline",
    "how hydroelectric dams generate electricity",
    "the pasteurization of milk",
    "how semiconductor transistors work",
    # recipes, procedures
    "the procedure for making sourdough bread",
    "how to prune a fruit tree in winter",
    "the steps to change a car tire",
    "the standard procedure for brewing pour-over coffee",
    "how to rotate crops on a small farm",
    "the method for tuning a violin",
    "the process of composting kitchen scraps",
    "how to wire a three-way light switch",
    "the standard routine for oil changes in a passenger vehicle",
    "how to set up a small aquarium",
]

NEUTRAL_PROMPT = """Write a short factual, emotionally flat paragraph (about 150 words) describing {topic}. Use neutral, encyclopedic, third-person prose. No characters, no narrative, no emotional language. Just facts, definitions, and mechanisms.

Return only the paragraph — no heading, no quotes."""


async def gen_one(prompt: str, attempt: int = 0) -> str:
    try:
        resp = await client.chat.completions.create(
            model=MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.9 if attempt == 0 else 1.0,
            max_tokens=400,
        )
        return resp.choices[0].message.content.strip()
    except Exception as e:
        if attempt < 2:
            await asyncio.sleep(1 + attempt)
            return await gen_one(prompt, attempt + 1)
        raise


async def gen_emotion_story(emotion: str, setting: str):
    text = await gen_one(EMOTION_PROMPT.format(emotion=emotion, setting=setting))
    return {"emotion": emotion, "setting": setting, "text": text}


async def gen_neutral_story(topic: str):
    text = await gen_one(NEUTRAL_PROMPT.format(topic=topic))
    return {"topic": topic, "text": text}


async def main():
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    rng = random.Random(42)

    # Emotion corpus
    emotion_tasks = []
    for emotion in EMOTIONS:
        settings = rng.sample(EMOTION_SETTINGS, N_STORIES_PER_EMOTION)
        for s in settings:
            emotion_tasks.append(gen_emotion_story(emotion, s))
    print(f"Generating {len(emotion_tasks)} emotion stories…", flush=True)

    # Run in chunks of 40 concurrent
    emotion_results = []
    for i in range(0, len(emotion_tasks), 40):
        chunk = emotion_tasks[i : i + 40]
        emotion_results.extend(await asyncio.gather(*chunk))
        print(f"  emotion stories done: {len(emotion_results)}/{len(emotion_tasks)}", flush=True)

    with open(EMOTION_STORIES_PATH, "w") as f:
        json.dump(emotion_results, f, indent=1, ensure_ascii=False)
    print(f"Wrote {EMOTION_STORIES_PATH}")

    # Neutral corpus
    topics = []
    base = NEUTRAL_TOPICS
    while len(topics) < N_NEUTRAL_STORIES:
        topics.extend(rng.sample(base, len(base)))
    topics = topics[:N_NEUTRAL_STORIES]

    neutral_tasks = [gen_neutral_story(t) for t in topics]
    print(f"Generating {len(neutral_tasks)} neutral stories…", flush=True)
    neutral_results = []
    for i in range(0, len(neutral_tasks), 40):
        chunk = neutral_tasks[i : i + 40]
        neutral_results.extend(await asyncio.gather(*chunk))
        print(f"  neutral stories done: {len(neutral_results)}/{len(neutral_tasks)}", flush=True)

    with open(NEUTRAL_STORIES_PATH, "w") as f:
        json.dump(neutral_results, f, indent=1, ensure_ascii=False)
    print(f"Wrote {NEUTRAL_STORIES_PATH}")


if __name__ == "__main__":
    asyncio.run(main())
